### ISSUE TITLE
[As-run] contents

### ISSUE THREAD

**Issue by Koulil77** [syfTec/TheCore-Alterpop#1]
Alterpop repport that all contents for all asruns files are the same for the 2 differents channels.

NOLLYWOOD --> BOX3
NOVELAS3 --> BOX0

**Comment by max-verem** [comment]
this happens because as run logs scripts runs same time but use same tmp file.

i fixed scripts

which periods of as run logs should be regenerated?

**Comment by Koulil77** [comment]
did you updated scripts on alterpop server ?
I've asked about periods.

**Comment by Koulil77** [comment]
Could you please regenerate ASRUN from January 1st ?

**Comment by Koulil77** [comment]
Did u regenerate ASRUN ?

Thx

**Comment by max-verem** [comment]
> Did u regenerate ASRUN ?

did

> for last 150 days....

**Comment by Koulil77** [comment]
I've sent an email to Alterpop to inform.
Thx
