### ISSUE TITLE
[CUISINES Channel] 4/3 intead of 16/9

### ISSUE THREAD

**Issue by Koulil77** [syfTec/TheCore-Alterpop#4]
Alterpop has reported that this clip https://we.tl/t-ozs38Bk6f4 has been played at 4/3 instead of 16/9.

Channel: Cuisines
Playlist Time; 07h59

Could you please check ?

**Comment by max-verem** [comment]
file provided in **SD**

i also have such problem with old videos....

i did manual fix:
```
[root@TheCore8CH bin]# diff -uNr TheCoreLibTemplateBuilder.pl.origin TheCoreLibTemplateBuilder.pl
--- TheCoreLibTemplateBuilder.pl.origin 2019-11-13 12:56:39.197108728 +0100
+++ TheCoreLibTemplateBuilder.pl        2019-11-13 12:57:38.945805989 +0100
@@ -412,7 +412,8 @@
             }
             else
             {
-                $tmpl_main->param(force_aspect_ratio => $meta->{'TheCoreIO.mode_par'});
+#                $tmpl_main->param(force_aspect_ratio => $meta->{'TheCoreIO.mode_par'});
+                $tmpl_main->param(force_aspect_ratio => "\@64/45");
             };
         }
         elsif('PAL43' eq $meta->{'current.clip.ar'})

[root@TheCore8CH bin]#
```
that assume that SD videos in 16:9

**Comment by Koulil77** [comment]
this is related to video or TheCoreLibTemplateBuilder.pl ?

**Comment by max-verem** [comment]
that is related to overriding aspect ratios.... very complex chain...

**Comment by Koulil77** [comment]
Then you will always force aspect ratio

**Comment by max-verem** [comment]
yes and no :-))

**Comment by Koulil77** [comment]
This is a commercial answer ;-)

**Comment by max-verem** [comment]
it is a long story about reference mov files that are 16:9 in contrainer  but 4:3 in DV stream...

there is even a special field in Box where current playlist convertor put aspect ratio value **ASTERISTK** that is special value...

**Comment by Koulil77** [comment]
Then I can answer to Alterpop and says that the error is in the container. Right ?

**Comment by max-verem** [comment]
if you need answer for Alterpop, then you can say them: system force pixel aspect ratio 1:1 because of it forced from playlist, we did workaround that will make all SD videos 64:45
