### ISSUE TITLE
[MANUAL FTP TRANSFER] Playout lag

### ISSUE THREAD

**Issue by Koulil77** [syfTec/TheCore-Alterpop#5]
Alterpop technician says that when he transfer the media manually via windows explorer. The transfer causes the playout to lag from time to time (short delays and short audio losses). Then the media is cut before the end.

Do you have an idea of ​​why? Is there a possibility of manual transfers via FTP to limit speed and avoid impacts in diff?

**Comment by max-verem** [comment]
did you enabled write-back cache on RAID controller?

**Comment by Koulil77** [comment]
do you think this can be done using areca cli tool on On-Air system without any impact ?

**Comment by Koulil77** [comment]
here is the RAID configuration:

```
System Beeper Setting           : Enabled
Background Task Priority        : Low(20%)
JBOD/RAID Configuration         : RAID
SATA NCQ Support                : Enabled
HDD Read Ahead Cache            : Enabled
Volume Data Read Ahead          : Normal
HDD Queue Depth                 : 1(Disabled)
Empty HDD Slot LED              : ON
CPU Fan Detection               : Enabled
SAS Mux Setting                 : Auto
SES2 Support                    : Enabled
Max Command Length              : 1M
Auto Activate Incomplete Raid   : Disabled
Disk Write Cache Mode           : Auto
Write Same For Initialization   : SAS And SATA
PCIE Gen3                       : Enabled
Hot Plugged Disk For Rebuilding : Blank Disk Only
Disk Capacity Truncation Mode   : Multiples Of 10G
Smart Option For HDD            : Failed The Drive
Smart Polling Interval          : On Demand
```

**Comment by max-verem** [comment]
> do you think this can be done using areca cli tool on On-Air system without any impact ?

i think so...

**Comment by Koulil77** [comment]
```
Areca: In archttp under "System Controls" -> "System Configuration" there's the option "Disk Write Cache Mode" (defaults "Auto")

"Off": disk write cache is turned off

"On": disk write cache is enabled, this is not safe for your data but fast

"Auto": If you use a BBM (battery backup module, which you really should use if you care about your data), the controller automatically turns disk writes off, to protect your data. In case no BBM is attached, the controller switches to "On", because neither controller cache nor disk cache is safe so you don't seem to care about your data and just want high speed (which you get then).

That's a very sensible default so you can let it "Auto" or enforce "Off" to be sure.
```

**Comment by Koulil77** [comment]
Do you suggest me to enable=on ?

**Comment by max-verem** [comment]
Write-back cache should be enabled

Next we need possible to turn off swap (swapoff and comment out fstab section)

Next re-read Alain's issue and possible we have to add env var:
```
MALLOC_ARENA_MAX=2
```
to TheCoreIO instances

**Comment by Koulil77** [comment]
> Write-back cache should be enabled

I'll enable Write-back cache

> Next we need possible to turn off swap (swapoff and comment out fstab section)

![image](https://user-images.githubusercontent.com/28648390/68873718-5541ee00-0700-11ea-92a8-4e09d3a28fe5.png)

**Comment by Koulil77** [comment]
Write-back cache is enabled now

```
===============================================================================

CLI> sys diskcache p=1
GuiErrMsg<0x00>: Success.

CLI> sys showcfg
The System Configuration
===============================================================================
System Beeper Setting           : Enabled
Background Task Priority        : Low(20%)
JBOD/RAID Configuration         : RAID
SATA NCQ Support                : Enabled
HDD Read Ahead Cache            : Enabled
Volume Data Read Ahead          : Normal
HDD Queue Depth                 : 1(Disabled)
Empty HDD Slot LED              : ON
CPU Fan Detection               : Enabled
SAS Mux Setting                 : Auto
SES2 Support                    : Enabled
Max Command Length              : 1M
Auto Activate Incomplete Raid   : Disabled
Disk Write Cache Mode           : Enabled
Write Same For Initialization   : SAS And SATA
PCIE Gen3                       : Enabled
Hot Plugged Disk For Rebuilding : Blank Disk Only
Disk Capacity Truncation Mode   : Multiples Of 10G
Smart Option For HDD            : Failed The Drive
Smart Polling Interval          : On Demand
===============================================================================
GuiErrMsg<0x00>: Success.

```

**Comment by Koulil77** [comment]
env var `MALLOC_ARENA_MAX=2` is alreadu set on IO's

**Comment by max-verem** [comment]
we can postpone NUMA settings

also there is a system parameter that control system cache for writing.... i need to recall it....

**Comment by Koulil77** [comment]
ok

**Comment by max-verem** [comment]
> we can postpone NUMA settings

i think we need to return to that

recall please motherboard used and which slots used for boards.

**Comment by max-verem** [comment]
![picturemessage_ujcunsh3 zid](https://user-images.githubusercontent.com/10303377/69007120-32068100-0942-11ea-843e-8a7c12a77e5e.png)

ARECA - CPU1, SLOT2
GPU - CPU2, SLOT4
QUAD2 - CPU2, SLOT6

**Comment by max-verem** [comment]
I suggest you to setup NUMA configuration as follow:

NUMA NODE **0** (CPU **1**)
* IO0
* IO2
* IO4
* IO6
* IO8
* BOX2
* BOX4
* BOX6
* BOX8
* FEEDER2
* FEEDER4
* FEEDER6
* FEEDER8

NUMA NODE **1** (CPU **2**)
* MATRIX
* SDI-OUT-1
* SDI-OUT-2
* SDI-OUT-3
* SDI-OUT-4
* SDI-OUT-5
* SDI-OUT-6
* SDI-OUT-7
* SDI-OUT-8
* IO1
* IO3
* IO5
* IO6
* BOX1
* BOX3
* BOX5
* BOX7
* FEEDER1
* FEEDER3
* FEEDER5
* FEEDER7

**Comment by max-verem** [comment]
and you have to find a time-slot to reboot server....

**Comment by Koulil77** [comment]
I have to ask Alterpop to find a solution to keep channels on air while we reboot the server.

**Comment by max-verem** [comment]
> I have to ask Alterpop to find a solution to keep channels on air while we reboot the server.

i dont understand their approach.... we (poor channel) have two systems...

why did not you discuss a maintenance of TheCore?
